# Generated by Django 3.1.4 on 2020-12-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='img_w',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', height_field='img_h', null=True, upload_to='profile_pics', width_field='img_w'),
        ),
    ]
