# Generated by Django 3.1.4 on 2020-12-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201211_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default=0, height_field='img_h', null=True, upload_to='main/post_pics', verbose_name='Foydalanuvhci rasmi', width_field='img_w'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='img_w',
            field=models.IntegerField(default=0),
        ),
    ]
