BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
        XXXX XXXXXXXXXX XXXX XXXX  XXXXXXXXXXXXXXXXXXXXXXXX
           
            XXXX XXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXX XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXBBB BBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                     FFFFFF
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
BBBBBBBB BBBBBBB