BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB
BBBB BBBBBB

BBBBB BBBBBBB
        XXXX XXXXXXXXXXXXXXXX XXXX XXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX  XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXX XXXXXX
                    XXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX X
                XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XX XXXXXXXXXXXXXXXXXXXXXXX

                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXBBB BBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXX
                        BBBBBBBBBB
                        FFFFFF
                         FFFFFF
                        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                    XXXXXXX
                XXXXXX
            XXXXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXX XXXXXXXXXX XXXXX XXXXXXX
            BBB BBBB BB BBBBB        
            XXXX XXXXXXXXXXX XXXX XXXXXXX XXXX XXXXXXXXX XXXXXXX XXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXX X
                    XXXX XXXXXX XXXXXXXXX
                         XXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXX XX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX FFFFFFF FF FFXXXXXXXX
                    BB BBBBBBBBBBB BB BBBBBBBBBBBB
                        XX XXXXXXBBB BBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXX XXXXXXXXXX XXXX  XXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                    XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXX XXXXXXXXXXXX FFFFFFFFFFFFFFFFFXXXX
                XXXXXX
            XXXXXX    
            BBBBB
                XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXX XXX XXXXX XXXX XXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            BBBBBB
        XXXXXX
        
BBBBBBBB BBBBBBB