BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBBBBBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXX XXXXX XXXX XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
    XXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXX XXXXXXXXXXXXXX XXX
XXXXXX
        XXXX XXXXXXXXXX XXXX XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX
            XXXX XXXXXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXXX XXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXBBB BBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    BBBBBBBBBB
                     FFFFFF
                    XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXX
            XXXXXX
        XXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBBBBB
XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
      XXX XXXXXXXX X XXXXXXXXXXXXXX

      XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXX X
          XXXXXXXXXXX XXXXXXXX
        XX
        XXXXXXXXX XXXXXXX
        XXXXXXXX XXXXXXXX XXXXXX X
          XX XXXXXXXXXXXXXXX X
            XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXX XXXX XXXX XXXX XXXXXXXX XXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXX XXXXXXXXXXXX
          X
        X
      XXX

    XXX
  XXXXXXXXX
BBBBBBBB BBBBBBBBBB